#Compiler
#--------------------

mpiCC = mpiCC

#Files
#--------------------
main = main.cpp



#Commands
#--------------------

all: main

part1: $(part1)
	$(mpiCC) $(part1) -o part1

part2: $(part2)
	$(mpiCC) $(part2) -o part2

part3: $(part3)
	$(mpiCC) $(part3) -o part3

part4: $(part4)
	$(mpiCC) $(part4) -o part4

main: $(main)
	$(mpiCC) $(main4) -o main_exe

clean: rm main_exe part1 part2 part3 part4

