#Compiler
#--------------------

mpiCC = mpiCC

#Files
#--------------------
part3 = part3.cpp


#Commands
#--------------------

all: part3

part1: $(part1)
	$(mpiCC) $(part1) -o part1

part2: $(part2)
	$(mpiCC) $(part2) -o part2

part3: $(part3)
	$(mpiCC) $(part3) -o part3

part4: $(part4)
	$(mpiCC) $(part4) -o part4

clean: rm main_exe part1 part2 part3 part4

