#Compiler
#--------------------

GCC = g++

#Files
#--------------------
main = main.cpp

#Commands
#--------------------

all: main_exe

main_exe: $(main)
	$(GCC) $(main) -o $@
		  
clean: rm main_exe
