#!/bin/sh

mpiexec -machinefile machines -np 1 ./main_exe 256 "The quick brown fox jumps over the lazy dog"

echo " "

string=$(cat paradiseLost.txt | tr "\"" "\\"\" | tr "'" "\'")
mpiexec -machinefile machines -np 1 ./main_exe 256 \"$string\"
echo " "
string=$(cat completeWorksOfShakespear.txt | tr "\"" "\\"\" | tr "'" "\'")
mpiexec -machinefile machines -np 1 ./main_exe 256 \"$string\"
