#!/bin/bash

mpiexec -machinefile machines -np 1 ./main_exe 256 "The quick brown fox jumps over the lazy dog"

echo " "

echo "Let's hash Paradise Lost, by John Milton"
for i in `seq 1 3`;
do
    foobar=$(cat paradiseLost.txt | tr "\"" "\\"\" | tr "'" "\'")
    string+=$foobar
    
    echo "using 256 bit outputs: using i = $i"

    for j in `seq 1 100`;
    do
        echo "n = $j"
        mpiexec -machinefile machines -np $j ./main_exe 256 \"$string\"
        echo " "
    done    

    echo "using 512 bit outputs, using i = $i"

    for j in `seq 1 100`;
    do
        echo "n = $j"
        mpiexec -machinefile machines -np $j ./main_exe 512 \"$string\"
        echo " "
    done   
done    

 
